"""
LS-DYNA keyword file generator.

Generates LS-DYNA input deck (*.k file) for explicit dynamics simulation.

Features:
- *NODE, *ELEMENT cards
- *PART, *SECTION definitions
- *MAT material cards
- *CONTACT definitions
- *LOAD and *BOUNDARY conditions
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional


class LSDYNAKeywordGenerator:
    """LS-DYNA keyword file generator."""

    def __init__(self):
        """Initialize LS-DYNA keyword generator."""
        self.nodes: List[tuple[int, float, float, float]] = []
        self.elements: List[tuple[int, int, List[int]]] = []
        self.parts: List[Dict[str, Any]] = []
        self.materials: List[Dict[str, Any]] = []
        self.contacts: List[Dict[str, Any]] = []
        self.loads: List[Dict[str, Any]] = []
        self.boundaries: List[Dict[str, Any]] = []

    def add_node(
        self,
        node_id: int,
        x: float,
        y: float,
        z: float,
    ) -> None:
        """Add node to model.

        Args:
            node_id: Node ID.
            x: X coordinate.
            y: Y coordinate.
            z: Z coordinate.
        """
        self.nodes.append((node_id, x, y, z))

    def add_element(
        self,
        element_id: int,
        part_id: int,
        node_ids: List[int],
    ) -> None:
        """Add element to model.

        Args:
            element_id: Element ID.
            part_id: Part ID.
            node_ids: List of node IDs (4 for tet4, 8 for hex8, etc.).
        """
        self.elements.append((element_id, part_id, node_ids))

    def add_part(
        self,
        part_id: int,
        section_id: int,
        material_id: int,
        name: str = "Part",
    ) -> None:
        """Add part definition.

        Args:
            part_id: Part ID.
            section_id: Section ID.
            material_id: Material ID.
            name: Part name.
        """
        self.parts.append({
            "id": part_id,
            "section_id": section_id,
            "material_id": material_id,
            "name": name,
        })

    def add_material(
        self,
        material_id: int,
        mat_type: str = "ELASTIC",
        density: float = 7.85e-9,  # Steel in tonne/mm^3
        youngs_modulus: float = 210000.0,  # MPa
        poisson_ratio: float = 0.3,
        yield_stress: Optional[float] = None,
    ) -> None:
        """Add material definition.

        Args:
            material_id: Material ID.
            mat_type: Material type (ELASTIC, PLASTIC_KINEMATIC, etc.).
            density: Material density.
            youngs_modulus: Young's modulus.
            poisson_ratio: Poisson's ratio.
            yield_stress: Yield stress (for plastic materials).
        """
        self.materials.append({
            "id": material_id,
            "type": mat_type,
            "density": density,
            "E": youngs_modulus,
            "nu": poisson_ratio,
            "yield": yield_stress,
        })

    def add_contact(
        self,
        contact_id: int,
        master_part: int,
        slave_part: int,
        contact_type: str = "AUTOMATIC_SURFACE_TO_SURFACE",
        friction: float = 0.0,
    ) -> None:
        """Add contact definition.

        Args:
            contact_id: Contact ID.
            master_part: Master part ID.
            slave_part: Slave part ID.
            contact_type: Contact type.
            friction: Coefficient of friction.
        """
        self.contacts.append({
            "id": contact_id,
            "type": contact_type,
            "master": master_part,
            "slave": slave_part,
            "friction": friction,
        })

    def write(
        self,
        filepath: str | Path,
        title: str = "LS-DYNA Model",
    ) -> Path:
        """Write LS-DYNA keyword file.

        Args:
            filepath: Output file path.
            title: Model title.

        Returns:
            Path to written file.
        """
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Ensure .k extension
        if filepath.suffix.lower() not in [".k", ".key"]:
            filepath = filepath.with_suffix(".k")

        with open(filepath, "w") as f:
            # Header
            f.write("*KEYWORD\n")
            f.write(f"*TITLE\n")
            f.write(f"{title}\n")
            f.write("$\n")
            f.write("$ Generated by KooCAD\n")
            f.write("$\n")

            # Control cards
            self._write_control_cards(f)

            # Materials
            if self.materials:
                self._write_materials(f)

            # Sections (placeholder)
            self._write_sections(f)

            # Parts
            if self.parts:
                self._write_parts(f)

            # Nodes
            if self.nodes:
                self._write_nodes(f)

            # Elements
            if self.elements:
                self._write_elements(f)

            # Contacts
            if self.contacts:
                self._write_contacts(f)

            # Loads
            if self.loads:
                self._write_loads(f)

            # Boundaries
            if self.boundaries:
                self._write_boundaries(f)

            # End
            f.write("*END\n")

        return filepath

    def _write_control_cards(self, f) -> None:
        """Write control cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ CONTROL CARDS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("*CONTROL_TERMINATION\n")
        f.write("$#  endtim    endcyc     dtmin    endeng    endmas\n")
        f.write("      10.0         0       0.0       0.0       0.0\n")
        f.write("$\n")

    def _write_materials(self, f) -> None:
        """Write material cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ MATERIALS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")

        for mat in self.materials:
            f.write(f"*MAT_{mat['type']}\n")
            f.write("$#     mid        ro         e        pr\n")
            f.write(f"{mat['id']:>10}{mat['density']:>10.3e}{mat['E']:>10.3e}{mat['nu']:>10.3f}\n")

            if mat.get('yield') and mat['type'] == "PLASTIC_KINEMATIC":
                f.write("$#    sigy      etan\n")
                f.write(f"{mat['yield']:>10.3e}       0.0\n")

            f.write("$\n")

    def _write_sections(self, f) -> None:
        """Write section cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ SECTIONS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("*SECTION_SOLID\n")
        f.write("$#   secid    elform\n")
        f.write("         1         1\n")
        f.write("$\n")

    def _write_parts(self, f) -> None:
        """Write part cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ PARTS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")

        for part in self.parts:
            f.write("*PART\n")
            f.write(f"${part['name']}\n")
            f.write("$#     pid     secid       mid\n")
            f.write(f"{part['id']:>10}{part['section_id']:>10}{part['material_id']:>10}\n")
            f.write("$\n")

    def _write_nodes(self, f) -> None:
        """Write node cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ NODES\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("*NODE\n")
        f.write("$#     nid               x               y               z\n")

        for node_id, x, y, z in self.nodes:
            f.write(f"{node_id:>8}{x:>16.6f}{y:>16.6f}{z:>16.6f}\n")

        f.write("$\n")

    def _write_elements(self, f) -> None:
        """Write element cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ ELEMENTS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("*ELEMENT_SOLID\n")
        f.write("$#     eid     pid      n1      n2      n3      n4      n5      n6      n7      n8\n")

        for elem_id, part_id, node_ids in self.elements:
            f.write(f"{elem_id:>8}{part_id:>8}")
            for nid in node_ids[:8]:  # Max 8 nodes per line
                f.write(f"{nid:>8}")
            f.write("\n")

        f.write("$\n")

    def _write_contacts(self, f) -> None:
        """Write contact cards.

        Args:
            f: File handle.
        """
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ CONTACTS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")

        for contact in self.contacts:
            f.write(f"*CONTACT_{contact['type']}\n")
            f.write("$#     cid                                                     fs        fd\n")
            f.write(f"{contact['id']:>10}                                            {contact['friction']:>10.3f}       0.0\n")
            f.write("$#    ssid      msid\n")
            f.write(f"{contact['slave']:>10}{contact['master']:>10}\n")
            f.write("$\n")

    def _write_loads(self, f) -> None:
        """Write load cards.

        Args:
            f: File handle.
        """
        if not self.loads:
            return

        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ LOADS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        # TODO: Implement load cards

    def _write_boundaries(self, f) -> None:
        """Write boundary condition cards.

        Args:
            f: File handle.
        """
        if not self.boundaries:
            return

        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        f.write("$ BOUNDARY CONDITIONS\n")
        f.write("$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
        # TODO: Implement boundary condition cards
