"""
OBJ/MTL file exporter.

Wavefront OBJ format with material library.

Features:
- OBJ geometry file
- MTL material library
- UV texture coordinates
- Vertex normals
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

from koocad.core.shape import Shape


class OBJExporter:
    """OBJ/MTL file exporter."""

    def __init__(
        self,
        export_materials: bool = True,
        export_normals: bool = True,
        export_uvs: bool = False,
    ):
        """Initialize OBJ exporter.

        Args:
            export_materials: Export MTL material file.
            export_normals: Export vertex normals.
            export_uvs: Export UV texture coordinates.
        """
        self.export_materials = export_materials
        self.export_normals = export_normals
        self.export_uvs = export_uvs

    def export(
        self,
        shape: Shape,
        filepath: str | Path,
        material: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Export shape to OBJ file.

        Args:
            shape: Shape to export.
            filepath: Output file path.
            material: Optional material properties.
            metadata: Optional metadata.

        Returns:
            Path to exported OBJ file.
        """
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Ensure .obj extension
        if filepath.suffix.lower() != ".obj":
            filepath = filepath.with_suffix(".obj")

        # Write OBJ file
        self._write_obj(filepath, shape, material, metadata)

        # Write MTL file if requested
        if self.export_materials:
            mtl_filepath = filepath.with_suffix(".mtl")
            self._write_mtl(mtl_filepath, material)

        return filepath

    def _write_obj(
        self,
        filepath: Path,
        shape: Shape,
        material: Optional[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]],
    ) -> None:
        """Write OBJ file.

        Args:
            filepath: Output file path.
            shape: Shape to export.
            material: Optional material properties.
            metadata: Optional metadata.
        """
        bbox = shape.bounding_box() if hasattr(shape, "bounding_box") else ((0, 0, 0), (1, 1, 1))
        min_pt, max_pt = bbox

        with open(filepath, "w") as f:
            # Header
            f.write("# Wavefront OBJ file\n")
            f.write("# Generated by KooCAD\n")
            f.write(f"# File: {filepath.name}\n")
            if metadata:
                title = metadata.get("title", "")
                if title:
                    f.write(f"# Title: {title}\n")
            f.write("\n")

            # Material library
            if self.export_materials:
                mtl_filename = filepath.with_suffix(".mtl").name
                f.write(f"mtllib {mtl_filename}\n")
                f.write("usemtl Material\n\n")

            # Vertices (placeholder triangle)
            f.write("# Vertices\n")
            f.write(f"v {min_pt[0]} {min_pt[1]} {max_pt[2]}\n")
            f.write(f"v {max_pt[0]} {min_pt[1]} {max_pt[2]}\n")
            f.write(f"v {min_pt[0]} {max_pt[1]} {max_pt[2]}\n")
            f.write("\n")

            # Normals
            if self.export_normals:
                f.write("# Normals\n")
                f.write("vn 0.0 0.0 1.0\n")
                f.write("vn 0.0 0.0 1.0\n")
                f.write("vn 0.0 0.0 1.0\n")
                f.write("\n")

            # UV coordinates
            if self.export_uvs:
                f.write("# Texture coordinates\n")
                f.write("vt 0.0 0.0\n")
                f.write("vt 1.0 0.0\n")
                f.write("vt 0.0 1.0\n")
                f.write("\n")

            # Faces
            f.write("# Faces\n")
            if self.export_normals and self.export_uvs:
                f.write("f 1/1/1 2/2/2 3/3/3\n")
            elif self.export_normals:
                f.write("f 1//1 2//2 3//3\n")
            elif self.export_uvs:
                f.write("f 1/1 2/2 3/3\n")
            else:
                f.write("f 1 2 3\n")

            # Metadata comment
            volume = shape.volume() if hasattr(shape, "volume") else 0.0
            f.write(f"\n# Volume: {volume:.6f} mm^3\n")
            f.write(f"# Bounding Box: {bbox[0]} to {bbox[1]}\n")
            f.write("# Note: CadQuery not installed - placeholder geometry\n")

    def _write_mtl(
        self,
        filepath: Path,
        material: Optional[Dict[str, Any]],
    ) -> None:
        """Write MTL material library file.

        Args:
            filepath: Output file path.
            material: Optional material properties.
        """
        # Default material
        if material is None:
            material = {
                "diffuse": (0.8, 0.8, 0.8),
                "specular": (0.5, 0.5, 0.5),
                "shininess": 32.0,
                "opacity": 1.0,
            }

        diffuse = material.get("diffuse", (0.8, 0.8, 0.8))
        specular = material.get("specular", (0.5, 0.5, 0.5))
        shininess = material.get("shininess", 32.0)
        opacity = material.get("opacity", 1.0)

        with open(filepath, "w") as f:
            f.write("# MTL material library\n")
            f.write("# Generated by KooCAD\n\n")

            f.write("newmtl Material\n")
            f.write(f"Kd {diffuse[0]} {diffuse[1]} {diffuse[2]}\n")  # Diffuse color
            f.write(f"Ks {specular[0]} {specular[1]} {specular[2]}\n")  # Specular color
            f.write(f"Ns {shininess}\n")  # Shininess
            f.write(f"d {opacity}\n")  # Opacity
            f.write("illum 2\n")  # Illumination model
